# Generated by Django 4.1.7 on 2023-03-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_rate",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_rate",
            field=models.IntegerField(default=1),
        ),
    ]
