# Generated by Django 4.1.6 on 2023-03-29 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_comment_comment_rate_alter_post_content_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewInProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='Categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(choices=[('NW', 'Новость'), ('AC', 'Статья')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_rate',
            field=models.IntegerField(default=0.0),
        ),
    ]
