# Generated by Django 4.1.6 on 2023-04-01 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_addnewinproject_category_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subject',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='Categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
