# Generated by Django 4.1.6 on 2023-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_subject_en_us_category_subject_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subject',
            field=models.CharField(help_text='category subject', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='subject_en_us',
            field=models.CharField(help_text='category subject', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='subject_ru',
            field=models.CharField(help_text='category subject', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_text',
            field=models.TextField(help_text='category content_text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_text_en_us',
            field=models.TextField(help_text='category content_text', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_text_ru',
            field=models.TextField(help_text='category content_text', null=True),
        ),
    ]
